version: '3.8'
services:
  ps_travel:
    build: .
    container_name: front_end
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    environment:
      - WATCHPACK_POLLING=true         
    stdin_open: true
    tty: true
  
  # keycloak:
  #     image: quay.io/keycloak/keycloak:15.0.2
  #     environment:       
  #       KEYCLOAK_USER: admin
  #       KEYCLOAK_PASSWORD: admin

  #     ports:
  #       - '8080:8080'     
  #     networks:
  #       - keycloak-network

# networks:
#   keycloak-network:
#     driver: bridge   
    

